### ISSUE TITLE
CURSA SKID

### ISSUE THREAD

**Issue by Tarkan-Zarrouk** [RimmerdaII/moloch.su-leak#3]
KKEKEKEKEKKEKEKEKEKEKEKEkK

**Comment by Zane2b2t** [comment]
Its a master7720 client what do u expect

**Comment by Tarkan-Zarrouk** [comment]
He didnt make this client LMAO

**Comment by Zane2b2t** [comment]
> He didnt make this client LMAO

Yes ik he skid it like everything he does
And its ironic that he has an "anarchy skid list" on his github
